[package]
name = "browsewith"
description = "Select what browser to use when opening links from applications."
version = "0.1.0"
authors = ["Luis Tavares"]
edition = "2018"
license = "MIT"

[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core.git", package = "glib" }
dirs = "1.0.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
reqwest = "0.11.8"
nix = "0.9.0"
#url = "2.2.2"
#futures = "0.3.19"

[dependencies.gtk]
version = "0.14.3"
features = ["v3_22_29"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "shellapi" ] }
windows = { version = "0.29.0", features = [ "Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com", "Foundation", "System", "System_RemoteSystems", "Networking" ] }
